#ifndef _KEY_DRV_ENCODER_H_
#define _KEY_DRV_ENCODER_H_

#define A_ENCODER_PORT	JL_PORTA
#define B_ENCODER_PORT 	JL_PORTA
#define A_ENCODER_BIT   BIT(6)
#define B_ENCODER_BIT   BIT(7)

#define ENCODER_INIT()   do{A_ENCODER_PORT->DIR |= (A_ENCODER_BIT);A_ENCODER_PORT->PD &= ~(A_ENCODER_BIT);A_ENCODER_PORT->PU |= (A_ENCODER_BIT);\
                           B_ENCODER_PORT->DIR |= (B_ENCODER_BIT);B_ENCODER_PORT->PD &= ~(B_ENCODER_BIT);B_ENCODER_PORT->PU |= (B_ENCODER_BIT);}while(0)

#define A_ENCODER_IN    ((A_ENCODER_PORT->IN & A_ENCODER_BIT))
#define B_ENCODER_IN    ((B_ENCODER_PORT->IN & B_ENCODER_BIT))

//
#define A_ENCODER_PORT_2	JL_PORTA
#define B_ENCODER_PORT_2 	JL_PORTA
#define A_ENCODER_BIT_2     BIT(4)
#define B_ENCODER_BIT_2     BIT(5)

#define ENCODER_INIT_2()    do{A_ENCODER_PORT_2->DIR |= (A_ENCODER_BIT_2);A_ENCODER_PORT_2->PD &= ~(A_ENCODER_BIT_2);A_ENCODER_PORT_2->PU |= (A_ENCODER_BIT_2);\
                            B_ENCODER_PORT_2->DIR |= (B_ENCODER_BIT_2);B_ENCODER_PORT_2->PD &= ~(B_ENCODER_BIT_2);B_ENCODER_PORT_2->PU |= (B_ENCODER_BIT_2);}while(0)

#define A_ENCODER_IN_2     ((A_ENCODER_PORT_2->IN & A_ENCODER_BIT_2))
#define B_ENCODER_IN_2     ((B_ENCODER_PORT_2->IN & B_ENCODER_BIT_2))

#endif

